deploy: change for github login

diff --git a/.github/workflows/build-push-deploy.yml b/.github/workflows/build-push-deploy.yml
--- a/.github/workflows/build-push-deploy.yml
+++ b/.github/workflows/build-push-deploy.yml
@@ -473,7 +473,9 @@ jobs:
             cd /home/tonont/$branch_name
             source .env
             echo "******Logging into GitHub Container Registry..."
-            echo "${CR_PAT}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+            echo "${CR_PAT}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin || {
+              echo "Docker login failed"; exit 1;
+            }
             echo "Pulling latest images of changed services..."
             echo "services to build: $services_to_build"
             # Remove the square brackets and split by comma
