deploy: change caddy host networking mode

diff --git a/.github/workflows/build-push-deploy.yml b/.github/workflows/build-push-deploy.yml
--- a/.github/workflows/build-push-deploy.yml
+++ b/.github/workflows/build-push-deploy.yml
@@ -534,9 +534,10 @@ jobs:
             services=\$(echo "$services_to_build" | tr -d '[]"' | tr ',' ' ')
             for service in $services; do
               full_service_name="${branch_name}_${service}"
-              echo "Updating service: ${service} in stack: $branch_name"
-              docker service update --force $full_service_name || echo "Failed to update service $service"
+              echo "Attempting to update service: $full_service_name"
+              docker service update --force "$full_service_name" || echo "Failed to update service $service"
             done
+
           
           EOF
 
